/**
 * AeroSpace adapter
 *
 * Consolidates AeroSpace detection, setup, notification, and theme config generation.
 * Uses configPaths for multi-location config support (~/.aerospace.toml and XDG).
 */

import path from 'path';
import os from 'os';
import { execSync } from 'child_process';
import type { AppAdapter } from '../adapter';
import type { ThemeColors } from '../../../shared/types';
import { APP_CONFIG } from '../../../shared/constants';
import { registerAdapter } from '../registry';
import { existsSync } from '../../utils/fs';

const homeDir = os.homedir();

/**
 * AeroSpace config search paths in priority order.
 * AeroSpace checks ~/.aerospace.toml first, then ~/.config/aerospace/aerospace.toml
 */
export const AEROSPACE_CONFIG_PATHS = [
  path.join(homeDir, '.aerospace.toml'),
  path.join(homeDir, '.config', 'aerospace', 'aerospace.toml'),
] as const;

export const aerospaceAdapter: AppAdapter = {
  name: 'aerospace',
  displayName: 'AeroSpace',
  category: 'tiling',

  installPaths: [
    '/Applications/AeroSpace.app',
    path.join(homeDir, 'Applications', 'AeroSpace.app'),
    '/opt/homebrew/bin/aerospace',
    '/usr/local/bin/aerospace',
  ],

  configPath: path.join(homeDir, '.config', 'aerospace', 'aerospace.toml'),

  configPaths: AEROSPACE_CONFIG_PATHS,

  templateFile: 'aerospace.toml',

  snippet: {
    code: `# Ricekit AeroSpace/JankyBorders integration
# Note: JankyBorders must be installed for border colors to work
# Install with: brew install FelixKratz/formulae/borders
after-startup-command = [
  'exec-and-forget source "$HOME/Library/Application Support/${APP_CONFIG.dataDirName}/current/theme/aerospace-borders.sh"'
]`,
    instructions: 'Add this to your aerospace.toml (or merge with existing after-startup-command):',
  },

  async notify(themePath: string, onLog?: (msg: string) => void): Promise<boolean> {
    try {
      const bordersScript = path.join(themePath, 'aerospace-borders.sh');
      if (existsSync(bordersScript)) {
        execSync(`bash "${bordersScript}"`, {
          shell: '/bin/bash',
          stdio: 'pipe',
          timeout: 5000,
        });
        onLog?.('✓ AeroSpace/JankyBorders theme applied');
        return true;
      }
      return false;
    } catch {
      return false;
    }
  },

  generateThemeConfig(colors: ThemeColors) {
    return {
      fileName: 'aerospace-borders.sh',
      content: generateAerospaceBordersConfig(colors),
    };
  },
};

export function generateAerospaceBordersConfig(colors: ThemeColors): string {
  const toArgb = (hex: string) => {
    const cleanHex = hex.replace('#', '');
    return `0xff${cleanHex}`;
  };

  const activeColor = toArgb(colors.accent);
  const inactiveColor = toArgb(colors.border || colors.brightBlack);

  return `#!/bin/bash
# AeroSpace/JankyBorders color configuration
# Generated by Ricekit
#
# This script configures JankyBorders to display themed window borders
# JankyBorders must be installed: brew install FelixKratz/formulae/borders
#
# Usage in aerospace.toml:
# after-startup-command = [
#   'exec-and-forget source "$HOME/Library/Application Support/Ricekit/current/theme/aerospace-borders.sh"'
# ]

# Color values (ARGB format: 0xAARRGGBB)
ACTIVE_COLOR="${activeColor}"
INACTIVE_COLOR="${inactiveColor}"
BORDER_WIDTH="5.0"

# Kill any existing borders process to allow theme updates without restart
pkill -x borders 2>/dev/null || true

# Small delay to ensure clean shutdown
sleep 0.2

# Find borders binary (check common Homebrew locations)
BORDERS_BIN=""
if [ -x "/opt/homebrew/bin/borders" ]; then
  BORDERS_BIN="/opt/homebrew/bin/borders"
elif [ -x "/usr/local/bin/borders" ]; then
  BORDERS_BIN="/usr/local/bin/borders"
elif command -v borders >/dev/null 2>&1; then
  BORDERS_BIN="borders"
fi

# Start borders with theme colors if found
if [ -n "$BORDERS_BIN" ]; then
  nohup "$BORDERS_BIN" active_color="$ACTIVE_COLOR" inactive_color="$INACTIVE_COLOR" width="$BORDER_WIDTH" >/dev/null 2>&1 &
  disown
fi
`;
}

registerAdapter(aerospaceAdapter);
