/**
 * SketchyBar adapter
 *
 * Consolidates SketchyBar detection, setup, notification, and theme config generation.
 */

import path from 'path';
import os from 'os';
import { execSync } from 'child_process';
import type { AppAdapter } from '../adapter';
import type { ThemeColors } from '../../../shared/types';
import { APP_CONFIG } from '../../../shared/constants';
import { registerAdapter } from '../registry';
import { existsSync } from '../../utils/fs';

const homeDir = os.homedir();

export const sketchybarAdapter: AppAdapter = {
  name: 'sketchybar',
  displayName: 'SketchyBar',
  category: 'system',

  installPaths: ['/usr/local/bin/sketchybar', '/opt/homebrew/bin/sketchybar'],

  configPath: path.join(homeDir, '.config', 'sketchybar', 'sketchybarrc'),

  templateFile: 'sketchybarrc',

  snippet: {
    code: `# Ricekit SketchyBar integration
source "$HOME/Library/Application Support/${APP_CONFIG.dataDirName}/current/theme/sketchybar-colors.sh"`,
    instructions: 'Add this near the top of your sketchybarrc (after #!/bin/bash):',
  },

  async notify(_themePath: string, onLog?: (msg: string) => void): Promise<boolean> {
    const sketchybarBin = sketchybarAdapter.installPaths.find((p) => existsSync(p));

    if (!sketchybarBin) {
      return false;
    }

    let sketchybarRunning = false;
    try {
      execSync('pgrep -x sketchybar', { stdio: 'pipe' });
      sketchybarRunning = true;
    } catch {
      // Not running
    }

    if (!sketchybarRunning) {
      return false;
    }

    try {
      execSync(`"${sketchybarBin}" --reload`, {
        stdio: 'pipe',
        timeout: 5000,
      });
      onLog?.('✓ SketchyBar reloaded');
      return true;
    } catch {
      return false;
    }
  },

  generateThemeConfig(colors: ThemeColors) {
    return {
      fileName: 'sketchybar-colors.sh',
      content: generateSketchybarConfig(colors),
    };
  },
};

export function generateSketchybarConfig(colors: ThemeColors): string {
  const toArgb = (hex: string) => {
    const cleanHex = hex.replace('#', '');
    return `0xff${cleanHex}`;
  };

  return `#!/bin/bash
# SketchyBar color configuration
# Source this file in your sketchybarrc: source "$CONFIG_DIR/colors.sh"
# Generated by Ricekit

# Color Definitions
export COLOR_BACKGROUND="${toArgb(colors.background)}"
export COLOR_FOREGROUND="${toArgb(colors.foreground)}"
export COLOR_ACCENT="${toArgb(colors.accent)}"
export COLOR_SELECTION="${toArgb(colors.selection)}"
export COLOR_BORDER="${toArgb(colors.border)}"

# Bar colors
export BAR_COLOR="${toArgb(colors.background)}"
export BAR_BORDER_COLOR="${toArgb(colors.border)}"

# Item colors
export ITEM_BG_COLOR="${toArgb(colors.selection)}"
export ICON_COLOR="${toArgb(colors.accent)}"
export LABEL_COLOR="${toArgb(colors.foreground)}"

# ANSI colors
export COLOR_BLACK="${toArgb(colors.black)}"
export COLOR_RED="${toArgb(colors.red)}"
export COLOR_GREEN="${toArgb(colors.green)}"
export COLOR_YELLOW="${toArgb(colors.yellow)}"
export COLOR_BLUE="${toArgb(colors.blue)}"
export COLOR_MAGENTA="${toArgb(colors.magenta)}"
export COLOR_CYAN="${toArgb(colors.cyan)}"
export COLOR_WHITE="${toArgb(colors.white)}"

# Bright ANSI colors
export COLOR_BRIGHT_BLACK="${toArgb(colors.brightBlack)}"
export COLOR_BRIGHT_RED="${toArgb(colors.brightRed)}"
export COLOR_BRIGHT_GREEN="${toArgb(colors.brightGreen)}"
export COLOR_BRIGHT_YELLOW="${toArgb(colors.brightYellow)}"
export COLOR_BRIGHT_BLUE="${toArgb(colors.brightBlue)}"
export COLOR_BRIGHT_MAGENTA="${toArgb(colors.brightMagenta)}"
export COLOR_BRIGHT_CYAN="${toArgb(colors.brightCyan)}"
export COLOR_BRIGHT_WHITE="${toArgb(colors.brightWhite)}"

# Transparent variants (50% alpha)
export COLOR_TRANSPARENT="${toArgb(colors.background).replace('0xff', '0x80')}"
export COLOR_SEMI_TRANSPARENT="${toArgb(colors.background).replace('0xff', '0xcc')}"
`;
}

registerAdapter(sketchybarAdapter);
